account/api/urls.py
from django.urls import path

from account.api.views import (
    CustomAuthToken, 
    UserRegisterAPIView,
    UpdateProfileView,
)

urlpatterns = [
    path('login/', CustomAuthToken.as_view(), name='auth_login'),
    path('register/', UserRegisterAPIView.as_view(), name='auth_register'),
    path('update-profile/<int:pk>/', UpdateProfileView.as_view(), name='auth_update_profile'),
]

account/urls.py
from django.urls import path, include, re_path
from django.contrib.auth.views import LogoutView
from account.views import (
    CustomLoginView,
    RegisterCreateView,
    UserActivate,
    CustomPasswordChangeView,
    PasswordChangeDone,
    CustomPasswordResetView,
    CustomPasswordResetDoneView,
    CustomPasswordResetCompleteView,
    CustomPasswordResetConfirmView
)


app_name = 'account'

urlpatterns = [
    path('register/', RegisterCreateView.as_view(), name='register'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('forget-password/', CustomPasswordResetView.as_view(), name='forget_ password'),
    re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,32})/$',
        UserActivate.as_view(), name='activate'),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("password-change/", CustomPasswordChangeView.as_view(), name="password_change"),
    path("password-reset-done/", PasswordChangeDone.as_view(), name="password_reset_done"),
    path("password-change-done/", CustomPasswordResetDoneView.as_view(), name="password_change_done"),
    path("password_reset_complete/", CustomPasswordResetCompleteView.as_view(), name="password_reset_complete"),
    re_path(r'password-reset-confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,32})/$', CustomPasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path('api/v1.0/', include('account.api.urls')),

]

damat_project/urls.py
import debug_toolbar
from django.contrib import admin
from django.conf.urls.i18n import i18n_patterns
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.i18n import JavaScriptCatalog
from rest_framework.authtoken import views


urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')), #Django translations URLS
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    path('social-auth/', include('social_django.urls', namespace="social")),
    path('api/v1.0/', include('product.api.urls', namespace='product_apis')),
    path('api/v1.0/', include('order.api.urls', namespace='order_apis')),
    path('api-auth/v1.0/', views.obtain_auth_token),
    path('api-auth/v1.0/', include('index.api.urls', namespace='index_apis')),
]


urlpatterns += i18n_patterns(
    path('jet/', include('jet.urls', 'jet')),  # Django JET URLS
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS
    path('admin/', admin.site.urls),
    path('', include('index.urls', namespace='index')),
    path('product/', include('product.urls', namespace='product')),
    path('order/', include('order.urls', namespace='order')),
    path('account/', include('account.urls', namespace='account')),
    path('contact/', include('contact.urls', namespace='contact')),
    path('__debug__/', include(debug_toolbar.urls)),

)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

index/urls.py
from django.urls import path, include
from index.views import (
    HomePageView,
    CompaignsShowView,
    dump_database_view,
)



app_name = 'index'


urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path("compaigns/", CompaignsShowView.as_view(), name="compaigns"),
    path('dump-database/', dump_database_view, name='dump_database_view'),
    path('api/v1.0/', include('index.api.urls')),
]

account/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, UnicodeUsernameValidator
from django.contrib.auth.models import PermissionsMixin
from django.utils.translation import gettext_lazy as _

from django.utils import timezone

from account.managers import UserManager


class User(AbstractUser):
    username_validator = UnicodeUsernameValidator  # username silmek(overwrite elemek)
    username = models.CharField(
        _('username'),
        max_length=150,
        blank=True,
        null=True,
        unique=False,
        help_text=_('Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.'),
        validators=[username_validator],
        error_messages={
            'unique': _("A user with that username already exists."),
        },
    )

    #informations
    email = models.EmailField(_('Email'), unique=True)
    first_name = models.CharField(_("Name"), max_length=50)
    last_name = models.CharField(_("Surname"), max_length=50)
    image = models.ImageField(_("Image"), upload_to='profile_photo', blank=True, null=True)
    phonenumber = models.CharField(_("Phone"), max_length=50)
    is_agreement = models.BooleanField(_("Agreement"), default=False)
    is_notifaction_email = models.BooleanField(_("Notifaction for email"), default=False)
    is_notifaction_phone = models.BooleanField(_("Notifaction for phone"), default=False)
    rewardpoints = models.IntegerField(_("rewardpoints"), default=0)
    

    #moderations
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    date_joined = models.DateTimeField(default=timezone.now)


    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = UserManager()

    def __str__(self):
        return self.email



class Customer(models.Model):
    user = models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE)
    name = models.CharField('Name', max_length=200, null=True, blank=True)
    email = models.CharField('Email', max_length=200, null=True, blank=True)
    device = models.CharField('Device', max_length=200, null=True, blank=True)
    # moderations
    status = models.BooleanField('Status', default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    class Meta:
        db_table = 'customer'
        verbose_name = 'Customer'
        verbose_name_plural = 'Customers'
        ordering = ('created_at',)
    def __str__(self):
        if self.name:
            name = self.name
        else:
            name = self.device
        return str(name)

account/forms.py
from django import forms
from django.db import models
from django.db.models import fields
from django.forms import widgets, TextInput, EmailInput, PasswordInput, CheckboxInput
from django.contrib.auth.forms import (
    UserCreationForm,
    AuthenticationForm,
    UsernameField,
    PasswordChangeForm,
    PasswordResetForm,
    SetPasswordForm,
)

from django.contrib.auth import get_user_model
from django.utils.translation import ugettext as _



User = get_user_model()


class RegisterForm(UserCreationForm):
    password1 = forms.CharField(required=True, widget=forms.PasswordInput(attrs={
        'name': "password",
        'class': "form-control js-password-input",
        'placeholder': "Şifre*"
    }))


    class Meta:

        model = User
        fields = [
            'email',
            'first_name',
            'last_name',
            'phonenumber',
            'is_agreement',
            'is_notifaction_email',
            'is_notifaction_phone'
        ]
        widgets = {
            'email':  EmailInput(
                attrs={
                    'name': 'email',
                    'class': 'form-control',
                    'placeholder': 'E-posta Adresi*'
                }
            ),
            'first_name': TextInput(
                attrs={
                    'name': "first_name",
                    'class': "form-control",
                    'placeholder': "İsim*",
                    'max_length': 50
                }
            ),
            'phonenumber' : TextInput(
                attrs={
                    'placeholder': 'Cep Telefonu Numaranız*',
                    'class': 'form-control js-phone-number', 
                    }),
            'last_name': TextInput(
                attrs={
                    'name': "last_name",
                    'class': "form-control",
                    'placeholder': "Soyisim**",
                    'max_length': 50
                }
            ),
            'is_agreement': CheckboxInput(
                attrs={
                    'name': 'confirm'
                }
            ),
            'is_notifaction_email': CheckboxInput(
                attrs={
                    'name': 'email_allowed'
                }
            ),
            'is_notifaction_phone': CheckboxInput(
                attrs={
                    'name': 'sms_allowed'
                }
            ),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        del self.fields['password2']


class LoginForm(AuthenticationForm):
    username = UsernameField(widget=forms.TextInput(attrs={
        'autofocus': True,
        'class': 'form-control',
        'placeholder': 'E-posta Adresi*',
        'name': 'email'
    }))
    password = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput(attrs={
            'autocomplete': 'current-password',
            'class': 'form-control',
            'name': 'password',
            'placeholder': 'Şifre*'
        }),
    )


class CustomPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(
        strip=False,
        widget=forms.PasswordInput(attrs={
            'class': 'input',
            'autocomplete': 'current-password', 
            'autofocus': True,
            'name': 'old_password',
            'placeholder': "Eski Şifre",
        }),
    )
    new_password1 = forms.CharField(
        strip=False,
        widget=forms.PasswordInput(attrs={
            'class': 'input',
            'autocomplete': 'current-password', 
            'placeholder': "Yeni Şifre",
            'name': "new_password1"
        }),
    )
    new_password2 = forms.CharField(
        strip=False,
        widget=forms.PasswordInput(attrs={
            'class': 'input',
            'autocomplete': 'current-password',
            'placeholder': "Yeni Şifre Tekrar",
            'name': "new_password2",
        }),
    )


class CustomPasswordResetForm(PasswordResetForm):
    email = forms.EmailField(
        max_length=254,
        widget=forms.EmailInput(attrs={
            'autocomplete': 'email',
            'class': "form-control",
            'placeholder': "E-posta Adresi*",
            'name': 'email',
            
        })
    )

    


class CustomSetPasswordForm(SetPasswordForm):
    new_password1 = forms.CharField(
        strip=False,
        widget=forms.PasswordInput(attrs={
            'class': 'input',
            'autocomplete': 'current-password', 
            'placeholder': "Yeni Şifre",
            'name': "new_password1"
        }),
    )
    new_password2 = forms.CharField(
        strip=False,
        widget=forms.PasswordInput(attrs={
            'class': 'input',
            'autocomplete': 'current-password',
            'placeholder': "Yeni Şifre Tekrar",
            'name': "new_password2",
        }),
    )

account/api/views.py
from django.contrib.auth import get_user_model
from rest_framework.authtoken.views import ObtainAuthToken
from rest_framework.response import Response
from rest_framework.permissions import IsAuthenticated, IsAuthenticatedOrReadOnly
from rest_framework.status import HTTP_200_OK
from rest_framework.generics import CreateAPIView, UpdateAPIView

from account.api.serializers import (
    UserDetailSerializer, 
    CreateUserSerializer,
    UpdateUserSerializer,
)

User = get_user_model()



class CustomAuthToken(ObtainAuthToken):

    def post(self, request, *args, **kwargs):
        serializer = self.serializer_class(data=request.data, context={'request': request})
        serializer.is_valid(raise_exception=True)
        user = serializer.validated_data['user']
        serializer = UserDetailSerializer(user, context={'request': request})

        return Response(serializer.data, HTTP_200_OK)


class UserRegisterAPIView(CreateAPIView):
    serializer_class = CreateUserSerializer


class UpdateProfileView(UpdateAPIView):

    queryset = User.objects.all()
    permission_classes = (IsAuthenticatedOrReadOnly,)
    serializer_class = UpdateUserSerializer

account/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import get_user_model
from django.contrib.auth.views import (
    LoginView, 
    PasswordChangeView, 
    PasswordChangeDoneView, 
    PasswordResetView, 
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)
from django.contrib.auth import authenticate, login as django_login
from django.utils.encoding import force_text
from django.utils.http import urlsafe_base64_decode
from django.urls import reverse_lazy
from account.tasks import send_confirmation_email
from django.contrib.messages import success, error

from account.forms import (
    RegisterForm,
    LoginForm,
    CustomPasswordChangeForm,
    CustomPasswordResetForm,
    CustomSetPasswordForm,
)
from django.views.generic import (
    CreateView,
    View,
    TemplateView, 
)

from account.tools.tokens import account_activation_token



User = get_user_model()


class RegisterCreateView(CreateView):
    model = User
    form_class = RegisterForm
    template_name = "register.html"
    success_url = reverse_lazy('account:login') 

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_active = False
        user.save()
        site_adres = self.request.is_secure() and "https://" or "http://" + self.request.META['HTTP_HOST']  # https://stackoverflow.com/
        send_confirmation_email(user, site_adres)

        return super().form_valid(form)


class UserActivate(View):

    def get(self, *args, **kwargs):
        uidb64 = kwargs.get('uidb64') 
        token = kwargs.get('token') 
        try:
            uid = force_text(urlsafe_base64_decode(uidb64))
            user = User.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None

        if user is not None and account_activation_token.check_token(user, token):
            user.is_active = True
            user.save()
            success(self.request, 'Email is activeted')
            return redirect(reverse_lazy('account:login'))
        else:
            error(self.request, 'Email is not activeted')
            return redirect(reverse_lazy('account:register'))



class CustomLoginView(LoginView):
    form_class = LoginForm
    template_name = 'login.html'


class CustomPasswordChangeView(PasswordChangeView):
    form_class = CustomPasswordChangeForm
    template_name = 'change_password.html'
    success_url = reverse_lazy('account:password_change_done')


class PasswordChangeDone(PasswordChangeDoneView):
    template_name = "password_change_done.html"


class CustomPasswordResetView(PasswordResetView):
    form_class = CustomPasswordResetForm
    template_name = 'forget_password.html'
    email_template_name ='email/password_reset_email.html'
    success_url = reverse_lazy('account:password_reset_done')


class CustomPasswordResetDoneView(PasswordResetDoneView):
    template_name = 'password_reset_done.html'


class CustomPasswordResetConfirmView(PasswordResetConfirmView):
    template_name = 'reset_password.html'
    form_class = CustomSetPasswordForm
    success_url = reverse_lazy('account:password_reset_complete')


class CustomPasswordResetCompleteView(PasswordResetCompleteView):
    template_name = 'password_reset_completed.html'


def logout(request):
    pass

account/templates/forget_password.html
{% extends 'base.html' %}
{% load static %}


{% block body %}
    <div class="js-base-content wrapper">

        <div class="container auth-page py-3 p-sm-4" id="ForgotPasswordPage">
            <div class="auth-page__title w-100">
                <h1>Şifremi Unuttum</h1>
                <span class="muted-text">Şifreni hatırlamıyorsan üyeliğini oluştururken
                    kullandığın e-posta adresini aşağıdaki alana yazın.</span>
            </div>
            <!-- id="ForgotPasswordForm" -->
            <form  action="" method="POST" class="auth-form w-100" novalidate="novalidate">
                {% csrf_token %}
                <!-- <input type="hidden" name="csrfmiddlewaretoken"
                    value="O1SWfIMhvoPgcwFxsrABo87HdMBqCxXefSeN2rbbXAOGQ3BPTEptmkdUhHvTym6E"> -->
                <label class="error" id="non_field_errors-error">{{form.non_field_errors}}</label>
                {% for field in form %}
                    <div class="form-group">
                        {{ field }}
                        {{ field.help_text }}
                        <ul>
                            {% for error in field.errors %}
                                <li> {{ error }} </li>
                            {% endfor %}
                        </ul>
                    </div>
                {% endfor %}
                <button type="submit" class="button mb-4 pz-button__action">Şifremi Gönder</button>
                <div class="form-group text-center">
                    <span class="muted-text">Şifreni hatırladın mı?</span>
                    <a href="/users/login/" class="link" rel="nofollow">
                        Giriş Yap
                    </a>
                </div>

            </form>

        </div>


        <div id="ForgotPasswordSuccessTemplate" class="d-none">
            <div class="auth-page__title w-100 py-5">
                <h1>Şifre yenileme e-postanız gönderildi.</h1>
                <span class="muted-text">Lütfen e-postanızı kontrol edip yenileme linkine tıklayınız.</span>
                <div>
                    <a href="/" class="link" rel="nofollow">
                        Ana Sayfaya Dön
                    </a>
                </div>
            </div>
        </div>


    </div>
{% endblock body %}

account/templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block body %}

    <div class="js-base-content wrapper">

        <div class="container auth-page py-3 p-sm-4" id="LoginPage">
            <div class="auth-page__title w-100">
                <h1>Üye Girişi</h1>
            </div>

            <form action="" class="auth-form w-100" method="POST" novalidate="novalidate">
                {% csrf_token %}
                {{form.non_field_errors}}
                
                <!-- <label class="error non_field_errors-error" id="non_field_errors-error" style="display: none;">
                </label> -->
                {% for field in form %}
                    <div class="form-group">
                        {{ field }}
                        {{ field.help_text }}
                        <ul>
                            {% for error in field.errors %}
                                <li> {{ error }} </li>
                            {% endfor %}
                        </ul>
                    </div>
                {% endfor %}
                <div class="form-group">
                    <a href="{% url 'account:forget_ password' %}" class="link">
                        Şifremi unuttum
                    </a>
                </div>
                <button type="submit" class="button pz-button__action">Giriş yap</button>
            </form>

            <div class="text-center my-3">
                <span class="muted-text">veya</span>
            </div>
            <a class="w-100" href="{% url 'social:begin' 'facebook' %}">
                <button type="button" class="button mb-3 button-outline">Facebook ile Bağlan</button>
            </a>
            <a class="w-100" href="{% url 'social:begin' 'google-oauth2' %}">
                <button type="button" class="button mb-3 button-outline">Google ile Bağlan</button>
            </a>
            <div class="text-center">
                <span class="muted-text">Üye değil misin?</span>
                <a href="{% url 'account:register' %}" class="link" rel="nofollow">
                    Yeni Üyelik Oluştur
                </a>
            </div>
        </div>

    </div>

{% endblock body %}

account/templates/password_change_done.html
{% extends 'base.html' %}
{% load static %}

{% block body %}
    <div class="js-base-content wrapper">

        <div class="container account__container">
            <div class="row">
                <div class="col-lg-2 account__menu d-lg-block">


                    <a class="account-menu__item-title" href="/account/">Hesabım</a>

                    <div class="account-menu__item-wrapper">
                        <span class="account-menu__item-title d-block"></span>
                        <ul class="js-account-menu-list account-menu__item-list">

                            <li>
                                <a class="account-menu__item-link d-block" href="/users/orders/">
                                    <i class="icon-cart account-menu__item-icon"></i>
                                    <span class="account-menu__item-text">Siparişlerim</span>
                                </a>
                            </li>

                            <li>
                                <a class="account-menu__item-link d-block" href="/users/old-orders/">
                                    <i class="icon-eski_siparislerim account-menu__item-icon"></i>
                                    <span class="account-menu__item-text">Eski Siparişlerim</span>
                                </a>
                            </li>

                            <li>
                                <a class="account-menu__item-link d-block" href="/account/profile/">
                                    <i class="icon-profile account-menu__item-icon"></i>
                                    <span class="account-menu__item-text">Üyelik Bilgilerim</span>
                                </a>
                            </li>

                            <li>
                                <a class="account-menu__item-link d-block" href="/account/address/">
                                    <i class="icon-adres_degistirme account-menu__item-icon"></i>
                                    <span class="account-menu__item-text">Adreslerim</span>
                                </a>
                            </li>

                            <li>
                                <a class="account-menu__item-link d-block" href="/account/favourite-products/">
                                    <i class="icon-heart account-menu__item-icon"></i>
                                    <span class="account-menu__item-text">Favorilerim</span>
                                </a>
                            </li>

                            <li>
                                <a class="account-menu__item-link d-block" href="/account/change-email/">
                                    <i class="icon-email_degistirme account-menu__item-icon"></i>
                                    <span class="account-menu__item-text">E-posta Değiştir</span>
                                </a>
                            </li>

                            <li>
                                <a class="account-menu__item-link d-block" href="/account/change-password/">
                                    <i class="icon-sifre_degistirme account-menu__item-icon"></i>
                                    <span class="account-menu__item-text active">Şifre Değiştir</span>
                                </a>
                            </li>

                            <li>
                                <a class="account-menu__item-link d-block" href="/account/coupons/">
                                    <i class="icon-kuponlar account-menu__item-icon"></i>
                                    <span class="account-menu__item-text">Kuponlarım</span>
                                </a>
                            </li>

                            <li>
                                <a class="account-menu__item-link d-block" href="/account/contact/">
                                    <i class="icon-bize_ulasin account-menu__item-icon"></i>
                                    <span class="account-menu__item-text">Bize Ulaşın</span>
                                </a>
                            </li>

                        </ul>
                    </div>

                </div>
                <div class="col-lg-10 account__content">

                    <h2>Şifre Değiştir</h2>
                    <p class="account__content__description">Şifreni değiştirmek için eski şifreni ve yeni şifreni iki defa
                        girip "Şifremi Değiştir” butonuna bas.</p>
                    <div id="changePasswordFormWrapper">
                        <form class="js-change-password-form" method="post" novalidate="novalidate">
                            <div class="form-group">
                                <h6 class="center">You password changed </h6>
                                <a class="btn btn-warning" href="{% url 'index:home' %}">Go to homepage</a>
                            </div>
                        </form>

                        <p class="js-form-message d-none">Değişiklikleriniz kaydedildi.</p>
                    </div>

                </div>
            </div>
        </div>

    </div>
{% endblock %}

account/templates/password_reset_completed.html
{% extends 'base.html' %}
{% load static %}


{% block body %}
<div class="js-base-content wrapper">

    <div class="container auth-page py-3 p-sm-4" id="ForgotPasswordPage">
        <div class="auth-page__title w-100 py-5">
            <h1>Şifreniz yenilendi.</h1>
            <!-- <span class="muted-text">Lütfen e-postanızı kontrol edip yenileme linkine tıklayınız.</span> -->
            <div>
                <a href="/" class="link" rel="nofollow">
                    Ana Sayfaya Dön
                </a>
            </div>
        </div>
    </div>


    <div id="ForgotPasswordSuccessTemplate" class="d-none">
        <div class="auth-page__title w-100 py-5">
            <h1>Şifreniz yenilendi.</h1>
            <!-- <span class="muted-text">Lütfen e-postanızı kontrol edip yenileme linkine tıklayınız.</span> -->
            <div>
                <a href="{% url 'index:home' %}" class="link" rel="nofollow">
                    Ana Sayfaya Dön
                </a>
            </div>
        </div>
    </div>


</div>
{% endblock body %}

account/templates/password_reset_done.html
{% extends 'base.html' %}
{% load static %}


{% block body %}
<div class="js-base-content wrapper">

    <div class="container auth-page py-3 p-sm-4" id="ForgotPasswordPage">
        <div class="auth-page__title w-100 py-5">
            <h1>Şifre yenileme e-postanız gönderildi.</h1>
            <span class="muted-text">Lütfen e-postanızı kontrol edip yenileme linkine tıklayınız.</span>
            <div>
                <a href="/" class="link" rel="nofollow">
                    Ana Sayfaya Dön
                </a>
            </div>
        </div>
    </div>


    <div id="ForgotPasswordSuccessTemplate" class="d-none">
        <div class="auth-page__title w-100 py-5">
            <h1>Şifre yenileme e-postanız gönderildi.</h1>
            <span class="muted-text">Lütfen e-postanızı kontrol edip yenileme linkine tıklayınız.</span>
            <div>
                <a href="{% url 'index:home' %}" class="link" rel="nofollow">
                    Ana Sayfaya Dön
                </a>
            </div>
        </div>
    </div>


</div>
{% endblock body %}