contact/urls.py
from django.urls import path
from contact.views import ContactCreateView

app_name = 'contact'

urlpatterns = [
    path("", ContactCreateView.as_view(), name="contact")
]

damat_project/urls.py
import debug_toolbar
from django.contrib import admin
from django.conf.urls.i18n import i18n_patterns
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.i18n import JavaScriptCatalog
from rest_framework.authtoken import views


urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')), #Django translations URLS
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    path('social-auth/', include('social_django.urls', namespace="social")),
    path('api/v1.0/', include('product.api.urls', namespace='product_apis')),
    path('api/v1.0/', include('order.api.urls', namespace='order_apis')),
    path('api-auth/v1.0/', views.obtain_auth_token),
    path('api-auth/v1.0/', include('index.api.urls', namespace='index_apis')),
]


urlpatterns += i18n_patterns(
    path('jet/', include('jet.urls', 'jet')),  # Django JET URLS
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS
    path('admin/', admin.site.urls),
    path('', include('index.urls', namespace='index')),
    path('product/', include('product.urls', namespace='product')),
    path('order/', include('order.urls', namespace='order')),
    path('account/', include('account.urls', namespace='account')),
    path('contact/', include('contact.urls', namespace='contact')),
    path('__debug__/', include(debug_toolbar.urls)),

)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

index/urls.py
from django.urls import path, include
from index.views import (
    HomePageView,
    CompaignsShowView,
    dump_database_view,
)



app_name = 'index'


urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path("compaigns/", CompaignsShowView.as_view(), name="compaigns"),
    path('dump-database/', dump_database_view, name='dump_database_view'),
    path('api/v1.0/', include('index.api.urls')),
]

index/templates/includes/footer.html
{% load static i18n %}
{% load custom_tags %}
<div class="footer">
    <footer>
        <div class="d-flex justify-content-lg-between flex-column flex-lg-row">
            <div class="footer__logo align-top d-flex">
                <i class="icon-logo"></i>
            </div>
            <nav class="flex-fill w-100">
                <ul
                    class="footer__menu d-flex flex-column flex-lg-row justify-content-center justify-content-lg-between text-lg-left text-center">
                    <li>
                        <div class="footer__menu__title js-footer-title">
                            {% trans 'KURUMSAL' %}
                            <i class="icon-chevron_down d-lg-none"></i>
                            <i class="icon-chevron_top d-lg-none"></i>
                        </div>
                        <ul class="footer__menu_subtitle">
                            <li>
                                <a href="hakkimizda/index.html" rel="nofollow">
                                    {% trans 'Hakkımızda' %}
                                </a>
                            </li>
                            <li>
                                <a href="address/stores/index.html">
                                    {% trans 'Mağazalarımız' %}
                                </a>
                            </li>
                            <li>
                                <a href="bilgi-toplumu-hizmetleri/index.html" rel="nofollow">
                                    {% trans  'Bilgi Toplumu Hizmetleri' %}
                                </a>
                            </li>
                            <li>
                                <a href="yeni-sezon-katalog.html">
                                    {% trans 'Katalog' %}
                                </a>
                            </li>
                            <li>
                                <a href="kaliplarimiz/index.html">
                                    {% trans 'Kalıplarımız' %}
                                </a>
                            </li>
                            <li>
                                <a href="kurumsal-satis/index.html" rel="nofollow">
                                    {% trans 'Kurumsal Satış' %}
                                </a>
                            </li>
                            <li>
                                <a href="sitemap.html">
                                    {% trans 'Site Haritası' %}
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <div class="footer__menu__title js-footer-title">
                            {% trans 'KOLEKSİYON' %}
                            <i class="icon-chevron_down d-lg-none"></i>
                            <i class="icon-chevron_top d-lg-none"></i>
                        </div>
                        <ul class="footer__menu_subtitle">
                            <li>
                                <a href="ds-classic/index.html">
                                    D&#39;S Classic
                                </a>
                            </li>
                            <li>
                                <a href="ds-casual/index.html">
                                    D&#39;S Casual
                                </a>
                            </li>
                            <li>
                                <a href="twn/index.html">
                                    TWN
                                </a>
                            </li>
                            <li>
                                <a href="ds-ceremony/index.html">
                                    D&#39;S Ceremony
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <div class="footer__menu__title js-footer-title">
                            {% trans 'MÜŞTERİ HİZMETLERİ' %}
                            <i class="icon-chevron_down d-lg-none"></i>
                            <i class="icon-chevron_top d-lg-none"></i>
                        </div>
                        <ul class="footer__menu_subtitle">
                            <li>
                                <a href="musteri-hizmetleri/index.html" rel="nofollow">
                                    {% trans 'Müşteri Hizmetleri' %}
                                </a>
                            </li>
                            <li>
                                <a href="gizlilik-ve-guvenlik/index.html" rel="nofollow">
                                    {% trans 'Gizlilik ve Güvenlik' %}
                                </a>
                            </li>
                            <li>
                                <a href="kisisel-verilerin-islenmesi-ve-koruma-politikasi/index.html"
                                    rel="nofollow">
                                    {% trans 'Kişisel Verilerin İşlenmesi ve Koruma Politikası' %}
                                </a>
                            </li>
                            <li>
                                <a href="kvkk-basvuru-formu/index.html" rel="nofollow">
                                    KVKK Başvuru Formu
                                </a>
                            </li>
                            <li>
                                <a href="teslimat-ve-kargo/index.html" rel="nofollow">
                                    {% trans 'Teslimat ve Kargo' %}
                                </a>
                            </li>
                            <li>
                                <a href="iptal-iade-bilgilendirme/index.html" rel="nofollow">
                                    İptal / İade
                                </a>
                            </li>
                            <li>
                                <a href="sorular/index.html">
                                    SSS
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'contact:contact' %}" rel="nofollow">
                                    {% trans 'İletişim' %}
                                </a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </nav>
            <div class="pr-lg-3 subscribe__box">
                <div>
                    <div class="text-left">
                        <div class="footer__menu__title">
                            SOSYAL MEDYA
                        </div>
                        <div class="social_box">
                            <a href="https://www.facebook.com/DSDamat" target="facebookWindow">
                                <i class="icon-facebook"></i>
                            </a>
                            <a href="https://twitter.com/ds_damat/" target="twitterWindow">
                                <i class="icon-twitter"></i>
                            </a>
                            <a href="https://www.instagram.com/dsdamatonline/" target="instagramWindow">
                                <i class="icon-instagram"></i>
                            </a>
                            <a href="https://www.youtube.com/user/DamatTweenIstanbul" target="instagramWindow">
                                <i class="icon-youtube"></i>
                            </a>
                        </div>
                    </div>
                </div>

                <div>
                    <div class="subscribe__text">
                        {% trans 'D’S Damat’a özel haberlerden,' %}
                        {% trans 'indirimlerden haberdar olmak için e-bültenimize üye olun.' %}
                    </div>

                    {% get_current_language as LANGUAGE_CODE %}
                    <form id="newsletter_subscribe" class="d-flex justify-content-lg-center" method="POST">
                        {% csrf_token %}
                        <div class="d-inline w-100">
                            <div class="d-flex">
                                <input id='email' type="email" name="email" required
                                    placeholder="E-posta Adresinizi Girin">
                                <button type="submit">
                                    {% trans 'GÖNDER' %}
                                </button>
                            </div>
                            <span id="error_messages"></span>
                        </div>
                    </form>
                    <script>
                        var domain = 'http://{{ request.META.HTTP_HOST }}/{{ LANGUAGE_CODE }}';

                        document.querySelector('#newsletter_subscribe').addEventListener('submit', async(e) => {
                            e.preventDefault()
                            let form = e.target;
                            let postData = {'email': form.email.value}
                            let csrfToken = document.querySelector('[name="csrfmiddlewaretoken"]').getAttribute('value');

                            let response = await fetch(`${domain}/api-auth/v1.0/subscribe/`, {
                                
                                headers: {
                                    'content-type': 'application/x-www-form-urlencoded; charset=utf-8',
                                    'X-CSRFToken': csrfToken
                                },
                                method: "POST",
                                body: JSON.stringify(postData)
                            });
                            data = await response.json()
                            if (response.status == 400){
                                errorMessage = data.email
                            }
                            else{
                                errorMessage = ''
                            }
                            document.querySelector('#error_messages').innerHTML = errorMessage
                            document.querySelector('#email').innerHTML = ''
                            console.log(data)
                        })


                    </script>
                </div>
                <div class="success_modal js-subs_modal d-none">
                    <div class="modal-wrapper">
                        <div class="border-bottom modal-head pl-3">
                            <h3>E-Bülten</h3>
                        </div>
                        <p class="text-center mt-4">
                            {% trans 'E-posta adresiniz sisteme kaydolmustur.' %}
                        </p>
                        <div class="text-center mt-4">
                            <a class="btn btn-dark text-center color-white">Ok</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="d-flex justify-content-lg-end">
            
            <img src="{% static 'images/tqlty.png' %}" alt="">
        </div>
        <div class="d-flex justify-content-between flex-column-reverse flex-lg-row">
            <div class="footer__copyright">
                © 2020 D’S Damat, {% trans 'bütün hakları saklıdır' %}.
                
            </div>

            <div class="footer__lang">
                <span>LANGUAGES</span>
                <form action="/i18n/setlang/" method="post" style="display: none" id="change_language_form">
                    {% csrf_token %}
                    <input type="hidden" value="" name="language" id="language" />
                </form>
                {% get_current_language as LANGUAGE_CODE %}
                {% get_available_languages as LANGUAGES %}
                {% get_language_info_list for LANGUAGES as languages %}
                {% for language in languages %}
                    <a href="#" lang_code="{{ language.code }}"  class="change_language">{{language.code | upper }}</a>
                {% endfor %}
                <script>
                    $('.change_language').click(function(e){
                        e.preventDefault();
                        $('#language').val($(this).attr('lang_code'));
                        $('#change_language_form').submit();
                    });
                </script>
            </div>
        </div>
    </footer>
</div>